// <auto-generated />
namespace CicleFem1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705180923511_datenullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
